### ISSUE TITLE
Add examples to docs

### ISSUE THREAD

**Issue by ianhi** [msbentsen/plotannot#1]
Hi,

very nice package! What do you think about adding the example notebook to the docs? You could either break it up into python files and use sphinx-gallery (setup example [here](https://github.com/matplotlib/matplotlib-extension-cookiecutter/blob/93486375b29bdef621de7f04109a0f00d6940b54/%7B%7Bcookiecutter.github_project_name%7D%7D/docs/conf.py#L44-L49)) or you can actually directly include the notebook in the docs using either nbsphinx or with myst-nb. 

I think the second option is probably a bit easier. Example here: https://github.com/ianhi/mpl-interactions/blob/9c48292d5c5931cd136da25961729858b7846abb/docs/conf.py#L70 will then render the notebooks in this directory as pages: https://github.com/ianhi/mpl-interactions/tree/main/docs/examples

**Comment by msbentsen** [comment]
Hi,

Thank you, I think that is a great idea! I ended up leaving the example notebooks in the main examples/ dir, but then linking them to the documentation using `nbsphinx-link`. I also added individual pages for notebooks, install and API to make the documentation a bit more streamlined. Notebooks are now integrated into the docs as seen here: https://plotannot.readthedocs.io/en/latest/examples/examples.html. Thank you for the suggestion!
